{% set name = "pystem" %}
{% set version = "0.0.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ebf4ff0456e2e27a04a939bd457b8aea8a851e139303ebd05fa276c1f94f30dd

build:
  number: 3
  skip: true  # [win or python_impl == 'pypy']
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - pip
    - python
    - fftw
    - numpy
    - setuptools
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.2.0
    - scikit-learn >=0.21.0
    - numba
test:
  imports:
    - pystem
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NingWang1990/pySTEM
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: A python module for segmentation of STEM images

  description: |
    Automatic segmentation of Scanning Transmission Electron 
    Microscope (STEM) images based on the local-correlation-map 
    descriptor
  doc_url: https://github.com/NingWang1990/pySTEM
  dev_url: https://github.com/NingWang1990/pySTEM

extra:
  recipe-maintainers:
    - jan-janssen
    - NingWang1990
    - freyso
